### ISSUE TITLE
Sysex file not loading 

### ISSUE THREAD

**Issue by elvislal** [francoisgeorgy/pacer-editor-v2#1]
Hi, I have tried uploading a sys file to configure my boss rc 505 to nectar pacer through the editor. However when im clicking the sysex button to load the sys file, nothing happens. Could you please help me out here to figure out how to solve this issue?

**Comment by francoisgeorgy** [comment]
Hi,
I'm at the hospital at the moment, I'll try to do my best to help you.
Can you post a screenshot and highlight the button you have problem with? 
If I understand correctly, you have a sysex file that you try to upload in the Pacer Editor, right? This is a Pacer dump sysex, right?
Which browser and OS are you using?

**Comment by elvislal** [comment]
Hi, Thank you for replying so quickly. Well i have attached the screenshot.
Let me know if you can see it. So I got a sysex file to configure my boss
rc 505 with Nektar pacer through this link:
https://www.dropbox.com/s/5vgj0gz97ixzz0i/pacer-patch.2020-10-19%20RC505.syx?dl=0
<https://www.youtube.com/redirect?q=https%3A%2F%2Fwww.dropbox.com%2Fs%2F5vgj0gz97ixzz0i%2Fpacer-patch.2020-10-19%2520RC505.syx%3Fdl%3D0&redir_token=QUFFLUhqbk9IekRtdm5nSHNWUnNnNjdUUFVkRVhCQ0VUZ3xBQ3Jtc0tsb1J1UGdCamFQNWVGSEluX1ExRENfS19uSmFyZy1MdGNKOFllVmZ4UXhWZzRMUWxrbk1tUnp0TGhYN0JYZlJ1bXJfQWt5QVVNYlNwM3E5MzVBMFpCVmZHZVE2LWJLbDAzeWcyS1NsZm1FM0p5Wng4bw%3D%3D&stzid=UgxtTSRnAGa5VMEbeCV4AaABAg.97E0Aq7NmZr9F028DvRUJ4&event=comments>

So the screen shot that you see is the default factory preset which the web
app is able to read and load but when I click the button to load the sysex
file, it does not do anything. I am using a chrome browser. However, when I
opened the same web app on safari the button worked and I could load the
sysex file. But I am aware safari is not able to work with the midi so that
was still pointless. So I tried manually editing the switch and tried
updating it to pacer but even that does not work. I tried factory
resetting the pacer itself and then tried editing the patches and updating
it but still, it does not do anything to the pacer.

I am currently using M1 max Macbook pro Monterey OS. Hope the above
information helps and is clear for you.

Awaiting your response.

Thank you









 Screenshot 2022-10-04 at 1.27.15 PM 1.png
<https://drive.google.com/file/d/10gl68NTvqdMBlZT7k8RYS50aR9hz_bSk/view?usp=drive_web>

**Comment by francoisgeorgy** [comment]
Hi,

I can not access your screenshot. But it's not really important.

I am able to load your sysex file without any problem (Chrome under macOS Monterey). Here is the result :

![image](https://user-images.githubusercontent.com/367480/193805763-348108e3-6289-4b6f-a1a3-10998c3e8972.png)

When I'm back home I can set the pacer editor in debug mode and see if any warning pop up when it load the sysex file. But, since everything displays fine, I think the sysex is perfectly fine.

Can you try with Chrome but, this time, with the developer console open. Press Alt+Cmd+J to open the console, and then select the "console" tab :

![image](https://user-images.githubusercontent.com/367480/193807144-3e87c542-9088-4453-8ecd-924d9649afd1.png)

Then load the sysex file and tell me if any message appears in the console. 

Francois

**Comment by francoisgeorgy** [comment]
Any news? feedback?

**Comment by elvislal** [comment]
Hey Hi,
Sorry for the late reply, I was out of town. Well, I tried loading the file
today and it worked. I think there was a update pending on the chrome
browser and hence when i was trying to click the button nothing was
happening. Anyways it seems to be working now. Thank you so much for your
time and quick response. If I come across any other issues I will let you
know.

Peace and have a great day.

**Comment by francoisgeorgy** [comment]
Glad to hear that it finally worked.

Cheers!
